In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Environment is working correctly!")

Matplotlib is building the font cache; this may take a moment.

Environment is working correctly!

In [4]:
df = pd.read_csv("../data/sms_spam_collection.csv")

In [5]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.shape

(5572, 2)

In [7]:
df.columns

Index(['label', 'message'], dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5572 non-null   str
 1   message  5572 non-null   str
dtypes: str(2)
memory usage: 87.2 KB

In [9]:
df.sample(5)

     label                                            message
3489   ham                Still i have not checked it da. . .
2818  spam  Gr8 Poly tones 4 ALL mobs direct 2u rply with ...
2507   ham                               Who u talking about?
2846   ham         Will be out of class in a few hours. Sorry
2119  spam  U can WIN £100 of Music Gift Vouchers every we...

In [10]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(403)

In [12]:
df.columns

Index(['label', 'message'], dtype='str')

In [13]:
df["label"].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [14]:
df.columns = ["label", "message"]

In [15]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...