In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Environment work correctly")

Environment work correctly

In [4]:
df = pd.read_csv("../data/sms_spam_collection.csv")

In [5]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.shape

(5572, 2)

In [7]:
df.columns

Index(['label', 'message'], dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5572 non-null   str
 1   message  5572 non-null   str
dtypes: str(2)
memory usage: 542.9 KB

In [9]:
df.sample(5)

     label                                            message
3395   ham  Bull. Your plan was to go floating off to IKEA...
3104   ham  U so lousy, run already come back then half de...
2045   ham                I can send you a pic if you like :)
2639   ham                            Am in gobi arts college
2005   ham  Goodmorning, today i am late for  &lt;DECIMAL&...

In [10]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(403)

In [12]:
df.columns

Index(['label', 'message'], dtype='str')

In [13]:
df["label"].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [14]:
df.columns = ["label", "message"]

In [15]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...